# Generated by Django 3.0.5 on 2020-04-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_pozycja_do_kupienia_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozycja_do_kupienia',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
